services:

  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
    depends_on:
      - db
      - zipkin
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      replicas: 6  # 3 réplicas da aplicação
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1.5'  # Limite de CPU por réplica (ajuste conforme hardware)
          memory: 1G  # Limite de memória por réplica
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - app
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./infra/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin
    hostname: zipkin
    container_name: zipkin
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '0.5GB'
    ports:
      - "9411:9411"
    networks:
      - app-network

volumes:
  db:
    driver: local
  grafana-storage:

networks:
  app-network:
    driver: bridge
