global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'  # Endpoint da app; ajuste se diferente
    static_configs:
      - targets: ['app:8080']  # Scrape nas réplicas via DNS